In [4]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
labelencoder=LabelEncoder()
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
nb_classes = 2

xy = pd.read_csv('mushrooms.csv')

a = xy.isnull().sum()

for col in xy.columns:
    xy[col] = labelencoder.fit_transform(xy[col])

array = xy.values.tolist()


y_data = []

for i in range(0, 8124):
    y_data.append([array[i][0]])

for i in range(0, len(array[0])):
    for j in range(0, len(array)):
        array[j][i] = float(array[j][i])

for row in array:
    del row[0]
    del row[0]
    del row[0]
    del row[1]
    del row[1]
    del row[1]
    del row[1]
    del row[3]
    del row[3]
    del row[3]
    del row[3]
    del row[3]
    del row[3]
    del row[3]
    del row[3]
    del row[3]
    del row[3]
    del row[3]
    del row[3]
    del row[3]



std_data = StandardScaler().fit_transform(array)
print(std_data)

x_data = std_data

print(x_data)
print(y_data)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)

    h, c, a = sess.run([hypothesis, predicted, accuracy],feed_dict={X: x_data, Y: y_data})
print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)



[[-0.19824983  1.49468272 -0.22899776]
 [ 1.76587407 -0.66903831 -0.22899776]
 [ 1.37304929 -0.66903831  0.05347685]
 ..., 
 [-0.19824983 -0.66903831  0.05347685]
 [-0.19824983  1.49468272 -1.35889624]
 [-0.19824983 -0.66903831  1.74832457]]
[[-0.19824983  1.49468272 -0.22899776]
 [ 1.76587407 -0.66903831 -0.22899776]
 [ 1.37304929 -0.66903831  0.05347685]
 ..., 
 [-0.19824983 -0.66903831  0.05347685]
 [-0.19824983  1.49468272 -1.35889624]
 [-0.19824983 -0.66903831  1.74832457]]
[[1], [0], [0], [1], [0], [0], [0], [0], [1], [0], [0], [0], [0], [1], [0], [0], [0], [1], [1], [1], [0], [1], [0], [0], [0], [1], [0], [0], [0], [0], [0], [1], [0], [0], [0], [0], [0], [1], [0], [0], [0], [0], [0], [1], [0], [0], [0], [0], [0], [0], [0], [0], [0], [1], [1], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [1], [0], [0], [1], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], 

0 0.363262
200 0.221833
400 0.156298
600 0.120178
800 0.0975296
1000 0.0820365
1200 0.0707766
1400 0.0622244
1600 0.0555083
1800 0.0500948
2000 0.0456384
2200 0.0419062
2400 0.0387352
2600 0.0360077
2800 0.0336371
3000 0.0315575
3200 0.0297187
3400 0.0280813
3600 0.0266138
3800 0.0252913
4000 0.0240933
4200 0.023003
4400 0.0220066
4600 0.0210925
4800 0.020251
5000 0.0194736
5200 0.0187535
5400 0.0180844
5600 0.0174612
5800 0.0168793
6000 0.0163348
6200 0.0158242
6400 0.0153443
6600 0.0148926
6800 0.0144666
7000 0.0140642
7200 0.0136834
7400 0.0133226
7600 0.0129804
7800 0.0126552
8000 0.0123458
8200 0.0120511
8400 0.0117701
8600 0.0115019
8800 0.0112455
9000 0.0110003
9200 0.0107655
9400 0.0105406
9600 0.0103247
9800 0.0101176
10000 0.00991848

Hypothesis:  [[ 0.98962945]
 [ 0.9898122 ]
 [ 0.9898892 ]
 ..., 
 [ 0.99048483]
 [ 0.98993951]
 [ 0.99004132]] 
Correct (Y):  [[ 1.]
 [ 1.]
 [ 1.]
 ..., 
 [ 1.]
 [ 1.]
 [ 1.]] 
Accuracy:  0.482029
